from app.services.content_generation.base import ContentProvider


class TemplateProvider(ContentProvider):
    """Deterministic, template-based generator. No external dependency —
    used when no LLM API key is configured."""

    name = "template"

    def generate_blog(self, topic: str, keywords: list[str], brand_voice: str | None) -> dict:
        keyword_line = ", ".join(keywords) if keywords else topic
        voice_note = f" written in a {brand_voice} tone" if brand_voice else ""
        title = f"{topic}: What Your Customers Actually Need to Know"
        body = (
            f"# {title}\n\n"
            f"## Introduction\n"
            f"Most brands talk about {topic} the same way — this post{voice_note} takes a sharper angle, "
            f"grounded in what customers searching for '{keyword_line}' are really trying to solve.\n\n"
            f"## Why It Matters\n"
            f"Explain the customer problem behind {topic}, and why solving it builds trust rather than "
            f"just visibility.\n\n"
            f"## How We Approach {topic}\n"
            f"Walk through your product/process specifics here — this is the section to make concretely "
            f"your own before publishing.\n\n"
            f"## Key Takeaways\n"
            f"- Summarize the core insight on {topic}\n"
            f"- Tie it back to the customer outcome\n"
            f"- Include a clear next step (SEO keywords: {keyword_line})\n\n"
            f"## Call to Action\n"
            f"Invite the reader to take the next step with your brand.\n\n"
            f"*Draft generated by AdSaarthi Content Studio — review and personalize before publishing.*"
        )
        return {"title": title, "body": body}

    def generate_ad_copy(self, product_or_offer: str, platform: str, brand_voice: str | None) -> dict:
        voice_note = f" ({brand_voice} tone)" if brand_voice else ""
        variants = {
            "instagram": [
                f"Meet {product_or_offer} — made for how you actually live.",
                f"{product_or_offer} is here. Swipe up before it's gone.",
                f"Your new favorite: {product_or_offer}.",
            ],
            "youtube": [
                f"Discover {product_or_offer} — the story behind why we built it.",
                f"{product_or_offer}: see it in action in 30 seconds.",
            ],
            "google_search": [
                f"Buy {product_or_offer} Online | Free Shipping",
                f"{product_or_offer} — Rated by Real Customers",
            ],
        }
        chosen = variants.get(platform, [f"Introducing {product_or_offer}."])
        title = chosen[0]
        body = "\n".join(f"{i + 1}. {v}{voice_note}" for i, v in enumerate(chosen))
        return {"title": title, "body": body}

    def generate_creator_brief(
        self,
        brand_name: str,
        brand_voice: str | None,
        campaign_objective: str,
        influencer_handle: str,
        influencer_style: str | None,
        content_format: str,
    ) -> dict:
        style_note = influencer_style or "their usual content style"
        title = f"Creator Brief for @{influencer_handle} — {brand_name}"
        body = (
            f"## Campaign Objective\n{campaign_objective.replace('_', ' ').title()}\n\n"
            f"## Brand Voice\n{brand_voice or 'Friendly, direct, benefit-led.'}\n\n"
            f"## Format\n{content_format.replace('_', ' ').title()}\n\n"
            f"## Creative Concept\n"
            f"Lean into {style_note} — open with a relatable hook tied to the product's core benefit, "
            f"show natural usage, and close with a clear, low-pressure call to action for {brand_name}.\n\n"
            f"## Talking Points\n"
            f"- What problem {brand_name} solves, in your own words\n"
            f"- One authentic personal use-case\n"
            f"- Where to find/buy (link/sticker in caption)\n\n"
            f"## Deliverables\n1x {content_format.replace('_', ' ')}, caption + relevant hashtags.\n\n"
            f"*Draft generated by AdSaarthi — requires your review before outreach.*"
        )
        return {"title": title, "body": body}

    def generate_image_concept(self, prompt: str, image_format: str, brand_name: str) -> dict:
        title = f"{brand_name} — {image_format.replace('_', ' ').title()} Visual Concept"
        body = (
            f"## Prompt\n{prompt}\n\n"
            f"## Format\n{image_format.replace('_', ' ').title()}\n\n"
            f"## Composition Notes\n"
            f"- Lead with the product/subject in the center third\n"
            f"- Use {brand_name}'s brand colors and logo in a corner watermark\n"
            f"- Keep text overlay under 20% of frame for readability\n\n"
            f"## Suggested Copy Overlay\n\"{prompt.strip().capitalize()}\"\n\n"
            f"*This is a structured creative brief — plug in an image generation API "
            f"(e.g. a diffusion model) to render the final asset from this spec.*"
        )
        return {"title": title, "body": body}
